# Generated by Django 2.2.10 on 2020-03-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='queue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('creator', models.CharField(max_length=255)),
                ('people', models.TextField()),
                ('openTime', models.PositiveSmallIntegerField()),
                ('closeTime', models.PositiveSmallIntegerField()),
                ('period', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
