# Generated by Django 2.2.10 on 2020-03-27 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SoftWay', '0002_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='last',
            field=models.PositiveSmallIntegerField(default=3),
            preserve_default=False,
        ),
    ]
