# Generated by Django 2.2.10 on 2020-03-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SoftWay', '0003_queue_last'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='lastM',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
