# Generated by Django 2.2.10 on 2020-03-29 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SoftWay', '0005_people_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queue',
            name='lastM',
        ),
        migrations.AlterField(
            model_name='queue',
            name='last',
            field=models.TextField(),
        ),
    ]
