# Generated by Django 2.2.10 on 2020-04-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SoftWay', '0006_auto_20200329_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
            ],
        ),
    ]
