# Generated by Django 2.2.10 on 2020-04-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SoftWay', '0007_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='time',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
